### ISSUE TITLE
(DDraw) Submarine Titans (gog) is black and white in game.

### ISSUE THREAD

**Issue by VictorRabotko** [dege-diosg/dgVoodoo2#16]
Hello,
I have an issue with Submarine Titans ( https://www.gog.com/game/submarine_titans ).
if I use dgvoodoo 2.54 then the game runs perfectly.
if I update dgvoodoo to v. 2.71 then game turnes to black and white (not graystyle, just two colors). 
There is no issue in game menu.

In game bug
![Снимок экрана (3)](https://user-images.githubusercontent.com/42329334/97264151-5b70a200-185f-11eb-8676-6e481a7b9e43.png)

dgvoodoo 2.54 normal gameplay. This is how it should be.
![Снимок экрана (4)](https://user-images.githubusercontent.com/42329334/97278401-b6f95a80-1874-11eb-8278-2d3fcc3a267f.png)

**Comment by dege-diosg** [comment]
Hi,

Do you have anything special enabled in the dgVoodoo config? Could you attach dgVoodoo.conf here plz?
I tested the game with default dg config and it worked fine for me. I don't have a single idea where the monochrome palette comes from.

I noticed though that this game doesn't work with non-unspecified dgv scaling mode or forced resolutions, because it's very sensitive to the physical window size. I improved the DD-hook layer, and now it works.

**Comment by VictorRabotko** [comment]
Hi,
I have tested all dgVoodoo versions. A bug exists since v2.55 to v2.71.3.
A last version that works with this game is v2.54. I don't know what changes have been done in v2.55, but since v2.55 bug exists.

ps: everytime when I update dgVoodoo I always delete dgVoodoo.conf and create a new one.
pps: Maybe dgVoodoo does not support multigpu system. I have a MSI bravo 15 notebook? But why dgVoodoo v2.54 works fine?

**Comment by dege-diosg** [comment]
dgVoodoo supports multigpu system, you can even select which gpu/display output(s) you want to enable.

Don't you have an AMD gpu? There is a known issue with them, starting from 2.55, erroneous texturing on AMD hw because of bad drivers.
What if you select D3D12 as output API in the config? It should work fine.

**Comment by VictorRabotko** [comment]
1. selecting D3D12 output API solves the problem. Thank you.
2. yes, I have an AMD gpu. I own a radeon gpus for more than 10 years and never had any issues with it, except two games (Submarine Titans and Incoming)
