### ISSUE TITLE
Virus complaining computer

### ISSUE THREAD

**Issue by martinbangens** [dege-diosg/dgVoodoo2#17]
I cant download latest release, and older release will download but wont run cus stupid windows 10 seem to be 100 sure there is virus in the zip file :D I don't believe it can you confirm you're zip file is clean?

**Comment by dege-diosg** [comment]
Yes, it's a known problem.

The main reason of moving dgVoodoo to GitHub is because of google is kindly treating my website as a malware container site <s>and I'm very gratefu</s>, relying on all kinds of trash noname AV craps, just have a look on VirusTotal.

Anyway, all the zip's are clean. I always submit new releases to MS for (human) analysis to remove false positive hits on Defender side. Can't care about other AV's.

**Comment by martinbangens** [comment]
It worked like a month ago. Sorry you get attacked by google like this, sorry for wasting you're time.
