### ISSUE TITLE
it is possible to display some modern games that are always in letterbox mode correctly in 4: 3,5:4 (1280x1024) without black bars?

### ISSUE THREAD

**Issue by JIuBeP** [dege-diosg/dgVoodoo2#31]
Hello! I know that my problem is very specific and most likely almost does not apply to this program, sorry. I just want to know if it is possible to display some modern games that are always in letterbox mode correctly in 4: 3,5:4 (1280x1024) without black bars? example: assassins creed series, dark souls 3, rayman legends/

**Comment by dege-diosg** [comment]
You mean displaying a widescreen image (with aspect ratio of 16:9 or such) in a 4:3 or 5:4?
Without black bars the image would just stretch to fill in the output, causing distorting it all. Why'd you want it?

Anyway, you can do it through dgVoodoo, otherwise it's up to the game if it supports that.
