### ISSUE TITLE
vmware workstation16 with dgVoodoo2 

### ISSUE THREAD

**Issue by happy2046** [dege-diosg/dgVoodoo2#33]
HI
vmware workstation16 support dx11,but when I use dgVoodoo2 in vm16,only dgVoodoo2 logo is showing and the other part of the 3d screen is all black.
I want to use dgVoodoo2  in vmware because vmware dx9 performance is very poor since  the version 12.0 and later but dx10 and 11 performance is good.
Would you please have a look at it to make sure wheather this is a vmware 3d driver issure or is there a workaround for this?

**Comment by dege-diosg** [comment]
Unfortunately I can't check it out ATM because I don't have VMWare installed.
But, if the same game works natively but not through VMWare then it's a driver issue.

You can try D3D11 MS Warp to see if it's working through sw rendering. It'll run very slow in windowed mode but it's another way to check if the hw driver is the source of the problem.

**Comment by happy2046** [comment]
d3d11 ms wrap works and this should be a vmware driver issure.
thanks.
