### ISSUE TITLE
more a qustion than an issue....

### ISSUE THREAD

**Issue by medievil1** [dege-diosg/dgVoodoo2#39]
if one receives, for example 
```[dgVoodoo] ERROR: Direct3DDevice9 (12B66128): Draw*/ProcessVertices: The current vertex declaration (12F91F28) does not define a valid fixed function vertex pipeline input layout.```
is there a way to see the input that triggered it?

**Comment by dege-diosg** [comment]
Yes: set Debug\MaxTraceLevel to 2 in the config file to enable logging the D3D API calls + some additional internal info coming from them.
Then, from the point of the error message backward, search for the first CreateVertexDeclaration call that factored VertexDeclaration(12F91F28). AFAIR, that call dumps the vertex elements to the log.

**Comment by medievil1** [comment]
ok it is obviously logging, next question where is the log stored?? I looked in the app folder where the exe and d3d.dll is located and nothign was there

**Comment by dege-diosg** [comment]
It's not stored, just dumped to the current debug output.
If you think about option Debug\LogToFile, well that's not implemented because the log can be so tremendous that logging to file could make using the logged application absolutely unusable.
It's much better to dump the log to the debugger or DebugView, DebugView++ that are optimized to receive large amount of debug output and display that asynchronously. Also, you can watch the log in realtime in unlike with logging into file, and you can copy any parts of the log anytime.
