### ISSUE TITLE
Renderdoc compat

### ISSUE THREAD

**Issue by Trass3r** [dege-diosg/dgVoodoo2#4]
Have you ever tried attaching Renderdoc to a game running on dgVoodoo2?
Seems like it fails to inject. Tested on Dungeon Keeper 2.
Could it work in theory or are there fundamental technical impediments?

**Comment by dege-diosg** [comment]
If it doesn't work with RenderDoc then I think it's a RenderDoc issue...

In theory it should work because dgVoodoo converts the apps into d3d11/12 that RenderDoc can catch like with any other apps.
Maybe the game you tried ran with elevated rights or sg like that that caused the fail.

**Comment by dege-diosg** [comment]
Not an issue of dgVoodoo.

**Comment by Trass3r** [comment]
Ok thanks for the reply. For some reason it does not recognize any graphics API.

**Comment by CookiePLMonster** [comment]
To be precise, this is _kind of_ a dgVoodoo issue - I looked into this in more detail today, and the reason RenderDoc cannot inject into dgVoodoo libs is because its IAT is lacking the `OriginalFirstThunk` field, and it's essential for RenderDoc to hook properly.

This could just be an issue of the compiler/linker used, though.

**Comment by Trass3r** [comment]
> This could just be an issue of the compiler/linker used, though.

Which is?

**Comment by dege-diosg** [comment]
It's VS2019.

But then I know what the problem is: the dll's are packed so the packer must have removed the needed information from the images.

**Comment by Trass3r** [comment]
Will there be unpacked releases then?

**Comment by dege-diosg** [comment]
No, I doubt it.
But I could attach here the files from the next version you need uncompressed.

**Comment by UnrealEgg** [comment]
Based on my investigation, RenderDoc appears to be incompatible with dgVoodoo2 because of the way dgVoodoo2's `d3d9.dll` is packaged.

The `d3d9.dll` distributed with dgVoodoo2 is UPX-packed. After unpacking, I found that the import table is reconstructed at runtime rather than existing in a normal PE layout. Since RenderDoc relies on its standard DLL hooking mechanism (primarily through the import table and `GetProcAddress` interception), the expected hook points are no longer available, preventing RenderDoc from installing several of its required hooks. As a result, frame capture and graphics debugging fail.

To verify this, I modified RenderDoc's hooking implementation. Instead of relying on the existing import-based mechanism, I installed inline hooks directly on the relevant functions, disabled the `GetProcAddress` hook, and forced `PERF_GetStatus_hook` to always return `0`. With these changes, the DX11 backend works correctly with dgVoodoo2, suggesting that the incompatibility is primarily caused by the current hooking strategy rather than any fundamental API incompatibility.

However, the same approach is not sufficient for the DX12 backend. Although the initial hooking succeeds, there appear to be additional initialization or interception issues later in the execution path that I have not yet identified.

From my perspective, there are two possible directions to improve compatibility:

1. dgVoodoo2 could provide an unpacked `d3d9.dll` (or a build that preserves a conventional import table), allowing RenderDoc's existing hook mechanism to function as intended.
2. RenderDoc could introduce an alternative hook path that does not depend on import-table reconstruction or `GetProcAddress` interception, making it more tolerant of packed or runtime-reconstructed DLLs.

At the moment, this appears to be a technical compatibility issue between RenderDoc's current hooking implementation and the way dgVoodoo2 packages its `d3d9.dll`, rather than an issue with the Direct3D APIs themselves.
r
