### ISSUE TITLE
Winmm Track Looping Issues

### ISSUE THREAD

**Issue by OpenRift412** [dege-diosg/dgVoodoo2#44]
Due to how dgvoodoo2 handles it's wrappers (in this case, ddraw.dll), this seems to cause issues with certain CD audio wrappers such as winmm.dll, namely [this variant](https://github.com/dippy-dipper/cdaudio-winmm). According to the developer of cdaudio-winmm, it is possible that DgVoodoo is negating the loop command before it can reach the game exe itself. Is there a way this could be fixed?

**Comment by dege-diosg** [comment]
dgVoodoo doesn't hook WinMM, so I don't understand how it could alter the MCI commands.
Do you have a CD-playback issue in a game coming only when dgVoodoo is active?

**Comment by OpenRift412** [comment]
> Do you have a CD-playback issue in a game coming only when dgVoodoo is active?
I do. In my case it's WinQuake. I use dgVoodoo's ddraw.dll to enable non-square pixel resolutions, which causes the CD music not to loop. It will play the first time, but when it loops, it plays again from the beginning for half a second and then completely stops. 

I tested it again, this time without dgVoodoo, and the music loops perfectly fine without issue. Are there any possible settings in dgVoodoo.conf that could be the culprit?

**Comment by dege-diosg** [comment]
Huh, that's an interesting case.
Currently I have no idea how dgVoodoo (or some different circumstance compared to native ddraw) can affect CD playback.
And also, I don't think there is any dgv option to play with in hope of fixing the problem. :(

I'll have a look at this game later to find answer.

**Comment by dippy-dipper** [comment]
Hi! 

I'm the developer of the cdaudio-winmm project.

The dgVoodoo2 compatibility issue seems to have been with the notify message that was used for wav/mp3 playback in the cdaudio player.

The player issued the following command:
mciSendStringA("play mp3track notify", NULL, 0, g_hMainWindow);

Then the message handler looked for "case MM_MCINOTIFY:" to update the player status.

I have revised my code to look for a mode change instead of a notify message and this seems to be compatible with DgVoodoo2 ddraw.dll.

**Comment by dege-diosg** [comment]
Hi,

Thanks for your effort and the change in your code!!!
But this means that dgVoodoo absorbs an MM_MCINOTIFY message somewhere.

I'll have a look at it later when I finish the work I'm currently doing.

**Comment by dippy-dipper** [comment]
I took the time to better analyze the situation and here are my findings:

Firstly the issue was not with the message being absorbed but rather sent/received in an endless loop.

This was the likely sequence of events:
1. cdaudio player plays wav/mp3 track and looks for a notify message to tell when the track has finished.
2. cdaudio player handless the message and informs the winmm wrapper that it should also send a notify message to the game telling it that the playback has finished.

Here is the issue: 
This second notify message is sent to all top-level windows. So whichever program is first in line looking for it absorbs it. It was poor design but seemed to work until the ddraw wrapper was used. This then likely changed the priorities and the cdaudio player ended up receiving this second message too causing the endless loop. At least thats my best theory.

So I think dgVoodoo2 is innocent. My coding was simply not taking into account that the second message could also be captured by the player itself in some situations.

**Comment by dege-diosg** [comment]
Thanks for the explanation!
