### ISSUE TITLE
Adding possibility to set a fractional FPS limit value

### ISSUE THREAD

**Issue by Lrflx** [dege-diosg/dgVoodoo2#73]
Thanks for all the recent updates! So as the title states, it'd be really nice to have an ability to set fractional values like 59,985 cause it really helps to reduce lag even further,  and at the same time helps to avoid problems in some games, where setting values like 59 can bring synchronization problems and stutters.

**Comment by dege-diosg** [comment]
When you select a resolution from the combobox in the CPL then the refresh values are stored in rational (integer + fractional) form (only displayed as a truncated integer to the user).

Well, at least, it was true until I switched from binary to .INI format config files. Indeed, you can only define an integer refresh rate there. But, I thought it wasn't a big problem because DXGI as a presentation system chooses the closest supported refresh rate which is probably a rational value. In other words, it's enough to define a refresh rate close to the real one and let DXGI do the rest, so it shouldn't be a practical problem.
But I'm not sure. What Windows version are you using?

**Comment by Lrflx** [comment]
I'm using the latest update of Windows 10 now. I can't say I have hard numbers to prove it, but subjectively if I set up fractional framecap through RTSS or Special K I get less percieved lag comparing to inner cap of Dgvoodoo. And actually I got into somewhat of a wormhole testing different combinations last week, I even want to deviate from from my original question a bit. Thing is, Special K supports setting up a flip discard mode and Nvidia Reflex in any game, which allows to reduce lag even more. And enabling G-Sync together with Nvidia Reflex through conjunction of Dgvoodoo and Special K works really well, even in some really old games! But I can't set up flip discard though, it just crashes everything immediately. Problem probably lies within Special K here, but I thought I read somewhere that Dgvoodoo supports setting flip discard from itself explicitly too? I tried to simply set up Dgvoodoo to borderless mode, but Special K still shows fullscreen G-Sync in windowed mode not working, and as I understand it's a main sign that flip mode is enabled.

**Comment by dege-diosg** [comment]
I confused your question (FPS limiter) with the refresh rates of the display modes, sorry...

Ok, I'll consider it, altough fractional values having effect looks very strange to me.

"but I thought I read somewhere that Dgvoodoo supports setting flip discard from itself explicitly too?"
With D3D11 I use plain discard swapeffect (DXGI_SWAP_EFFECT_DISCARD) to keep compatibility with Win7.
With D3D12 it's always flip-discard (DXGI_SWAP_EFFECT_FLIP_DISCARD) because D3D12 doesn't support plain discard.

It's also worth to mention that D3D12 is never true fullscreen, even in fullscreen mode the window is just put to full screen sized borderless state by the system runtime, so there are no many differences between D3D12 fullscreen/fake fullscreen.

**Comment by Lrflx** [comment]
Ok, thanks for clarifying everything! 
I think I first got info about fractional framecap from this article: https://blurbusters.com/howto-low-lag-vsync-on/
It definitely helped, so I started to use it ever since.
Hmm, Special K just crashes immediately when using D3D12 with recent build, I guess I'd need to inquire its author about it.

**Comment by Lrflx** [comment]
Thank you for adding this feature! Will test it more, but for now it works as intended.
