### ISSUE TITLE
Virtua Fighter 2 does not work

### ISSUE THREAD

**Issue by Lifeisstrange74** [dege-diosg/dgVoodoo2#89]
With dgVoodoo 2.75.1, Virtua Fighter 2 crashes on start up before it can enter the menu regardless of version.

OS: Windows 10 Home 21H1
GPU: NVIDIA GTX 1060 6GB
CPU: i5-8600K
RAM:16GB DD
dgVoodoo2 config:
[dgVoodoo.txt](https://github.com/dege-diosg/dgVoodoo2/files/7314681/dgVoodoo.txt)

**Comment by dege-diosg** [comment]
I tried it but it worked for me. Is the crash caused by dgVoodoo? You should try the _dbg version of dgVoodoo to see if there is an error in the log.

There is a known issue though: High details with 16bit display (presumably 3D acceleraton) cannot be selected in the game menu, a 'DDraw init error' message pops up instead.

**Comment by dege-diosg** [comment]
I remember now, what the problem was. The game can't handle too much resolutions when enumerating them and crashes.
So, you have to set option DirectXExt\ExtraEnumeratedResolutions to 'classics' to prevent it.
(In the CPL GUI you can enable additional extra pages by right click and select it from the context menu.)

Now it works, I use this executable:
https://community.pcgamingwiki.com/files/file/1302-virtua-fighter-2-direct3d-patchexecutable/

**Comment by Lifeisstrange74** [comment]
Yep, worked. 
what did you do for Virtua Fighter 1 PC though? that also seems to crash
